// Regenerates src/{schema,routes,params,types}.ts from OpenAPI.json.
// Refresh OpenAPI.json from a running sonm-api (with features.webhooks_enabled, or the
// webhook routes are missing): curl http://localhost:14702/openapi.json > OpenAPI.json
// Trimmed from @insertish/oapi (MIT, Paul Makles).
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const NOTICE =
  "// Generated by scripts/generate.mjs from OpenAPI.json. Do not edit.\n";

// anyOf -> oneOf keeps unions tight (upstream REWRITE_ANYOF=1)
const spec = JSON.parse(
  (await readFile("OpenAPI.json", "utf8")).replace(/"anyOf"/g, '"oneOf"'),
);

await writeFile(
  "src/schema.ts",
  NOTICE + astToString(await openapiTS(spec, { defaultNonNullable: false })),
);

const routes = [
  "import type { paths } from './schema.js';",
  "export type APIRoutes =",
];
const queryData = {};
const pathResolve = {};

for (const [path, ops] of Object.entries(spec.paths)) {
  const template = path.replace(/\{\w+\}/g, "${string}");
  const parts = path.split("/").length - 1;

  for (const [method, route] of Object.entries(ops)) {
    const op = `paths['${path}']['${method}']`;
    const status =
      Object.keys(route.responses).find((x) => x !== "default") || "default";
    const contentType = Object.keys(route.responses[status].content || {})[0];
    const response =
      status === "204" || !contentType
        ? "undefined"
        : `${op}['responses']['${status}']['content']['${contentType}']`;

    const query = (route.parameters || [])
      .filter((p) => p.in === "query")
      .map((p) => p.name);
    const params =
      [
        query.length && `${op}['parameters']['query']`,
        route.requestBody?.content?.["application/json"] &&
          `${op}['requestBody']['content']['application/json']`,
      ]
        .filter(Boolean)
        .join("|") || "undefined";

    const entry = `parts: ${parts}, params: ${params}, response: ${response} }`;
    routes.push(`| { method: '${method}', path: \`${template}\`, ${entry}`);
    if (/\{\w+\}/.test(path))
      routes.push(`| { method: '${method}', path: '-${path}', ${entry}`);

    queryData[path] = { ...queryData[path], [method]: query };
  }

  const segments = path.split("/").slice(1);
  (pathResolve[segments.length] ||= []).push(
    segments.map((key) => (/\{.*\}/.test(key) ? [key] : key)),
  );
}

await writeFile("src/routes.ts", NOTICE + routes.join("\n") + ";\n");
await writeFile(
  "src/params.ts",
  NOTICE +
    `export const pathResolve = ${JSON.stringify(pathResolve)};\n` +
    `export const queryParams = ${JSON.stringify(queryData)};\n`,
);
await writeFile(
  "src/types.ts",
  NOTICE +
    "import type { components } from './schema.js';\n" +
    Object.keys(spec.components.schemas)
      .map(
        (s) =>
          `export type ${s.replace(/\s/g, "_")} = components['schemas']['${s}'];`,
      )
      .join("\n") +
    "\n",
);
